src/CrowdSource.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CrowdSource.Services;
using CrowdSource.Data;
using CrowdSource.Models.CoreModels;
using CrowdSource.Models.CoreViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace CrowdSource.Controllers
{
    [Authorize(Roles="Administrator")]
    public class AdminController : Controller
    {
        private readonly IDataLogic _logic;
        private readonly ApplicationDbContext _context;
        private readonly IDbConfig _config;

        public AdminController(ILoggerFactory loggerFactory, IDataLogic logic, ApplicationDbContext context, IDbConfig config)
        {
            _logic = logic;
            _context = context;
            _config = config;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("Admin/Collection/{id}/Group")]
        public async Task<IActionResult> ListGroupsInOneCollection(int id, [FromQuery]string SearchFileName, [FromQuery]bool? ShowFlagged, [FromQuery]int? page)
        {

            ViewData["CollectionId"] = id;
            ViewData["SearchFileName"] = SearchFileName;
            ViewData["ShowFlagged"] = ShowFlagged ?? false;
            var groups = new List<Group>();
            IQueryable<Group> @query;
            Pager @pager; 
            if (ShowFlagged ?? false)
            {
                @query = _context.Groups.Where(g => g.Collection.CollectionId == id && g.FlagType != null);
            }
            else if (SearchFileName == null || SearchFileName == "")
            {
                @query = _context.Groups.Where(g => g.Collection.CollectionId == id);
            }
            else
            {
                @query = _context
                    .Groups
                    .FromSql("SELECT * FROM \"Groups\" WHERE \"GroupMetadata\"->>'ImgFileName' LIKE {0}", "%" + SearchFileName + "%")
                    .Where(g => g.Collection.CollectionId == id);       
            }
            var count = await @query.CountAsync();
            @pager = new Pager(count, page ?? 1, 20);
            ViewData["pager"] = @pager;
            groups = await query.OrderBy(g => g.GroupId).Skip(@pager.PageSkip).Take(@pager.PageSize).ToListAsync();
            return View("ListGroup", groups);
        }

        [Route("Admin/Group/{id}")]
        public IActionResult GroupDetails(int id)
        {
            //TODO: Authentication: Admin Only
            var versions = _logic.GetAllVersions(id);
            var versionsWithFields = new List<Dictionary<FieldType, string>>();
            foreach (var version in versions)
            {
                versionsWithFields.Add(_logic.GetVersionFields(version));
            }

            var vm = new GroupDetailsViewModel()
            {
                Group = _context.Groups.Single(g => g.GroupId == id),
                Versions = versionsWithFields,
                RawVersions = versions.ToList(),
                FieldTypes = _logic.GetAllFieldTypesByGroup(id)
            };

            return View("GroupDetails", vm);
        }

        [Route("Admin/Group/Delete/{id}")]
        public async Task<IActionResult> GroupDelete(int id)
        {
            var @group = await _context.Groups
                .Include(g=> g.Collection)
                .SingleOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View("GroupDeleteConfirm",@group);
        }

        [HttpPost]
        [Route("Admin/Group/Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GroupDeleteConfirmed(int id)
        {
            var @group = await _context.Groups
                .Include(g=>g.Collection)
                .SingleOrDefaultAsync(m => m.GroupId == id);
            var collectionId = @group.Collection.CollectionId;
            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();
            return RedirectToAction("ListGroupsInOneCollection",new { id = collectionId });
        }


        [Route("Admin/Group/UnsetError/{id}")]
        public async Task<IActionResult> UnsetGroupError(int id)
        {
            //TODO: auth admin
            var @group = await _context.Groups
                .SingleOrDefaultAsync(g => g.GroupId == id);
            @group.FlagType = null;
            await _context.SaveChangesAsync();
            return RedirectToAction("EditGroup", "CrowdSource", new { id = id });
        }


        [Route("Admin/Options")]
        public async Task<IActionResult> Options()
        {
            ViewData["ReviewEnabled"] = _config.Get("ReviewEnabled");
            ViewData["ReviewThreshold"] = _config.Get("ReviewThreshold");
            ViewData["Randomize"] = _config.Get("Randomize");
            return View();
        }

        [HttpPost]
        [Route("Admin/Options")]
        public async Task<IActionResult> OptionsSubmit([FromForm] string ReviewEnabled, [FromForm] string Randomize, [FromForm] int ReviewThreshold)
        {
            _config.Set("ReviewEnabled", ReviewEnabled);
            _config.Set("ReviewThreshold", ReviewThreshold.ToString());
            _config.Set("Randomize", Randomize);
            return RedirectToAction("Options");
        }

    }
}


public class Pager
{
    public int PageIndex { get; private set; }
    public int TotalPages { get; private set; }
    public int PageSize { get; private set; }

    public Pager(int count, int pageIndex, int pageSize)
    {
        PageIndex = pageIndex;
        TotalPages = (int)Math.Ceiling(count / (double)pageSize);
        PageSize = pageSize;
    }

    public bool HasPreviousPage
    {
        get
        {
            return (PageIndex > 1);
        }
    }

    public bool HasNextPage
    {
        get
        {
            return (PageIndex < TotalPages);
        }
    }
    public int PageSkip
    {
        get
        {
            return (PageIndex - 1) * PageSize;
        }
    }

}

src/CrowdSource.Web/Controllers/CollectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrowdSource.Data;
using CrowdSource.Models.CoreModels;
using Microsoft.AspNetCore.Authorization;

namespace CrowdSource.Controllers
{
    [Authorize(Roles="Administrator")]
    public class CollectionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CollectionsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Collections
        public async Task<IActionResult> Index()
        {
            return View(await _context.Collections.ToListAsync());
        }

        // GET: Collections/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collection = await _context.Collections
                .SingleOrDefaultAsync(m => m.CollectionId == id);
            if (collection == null)
            {
                return NotFound();
            }

            return View(collection);
        }

        // GET: Collections/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Collections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CollectionId,Name")] Collection collection)
        {
            if (ModelState.IsValid)
            {
                _context.Add(collection);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(collection);
        }

        // GET: Collections/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collection = await _context.Collections.SingleOrDefaultAsync(m => m.CollectionId == id);
            if (collection == null)
            {
                return NotFound();
            }
            return View(collection);
        }

        // POST: Collections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CollectionId,Name")] Collection collection)
        {
            if (id != collection.CollectionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(collection);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CollectionExists(collection.CollectionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(collection);
        }

        // GET: Collections/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var collection = await _context.Collections
                .SingleOrDefaultAsync(m => m.CollectionId == id);
            if (collection == null)
            {
                return NotFound();
            }

            return View(collection);
        }

        // POST: Collections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var collection = await _context.Collections.SingleOrDefaultAsync(m => m.CollectionId == id);
            _context.Collections.Remove(collection);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CollectionExists(int id)
        {
            return _context.Collections.Any(e => e.CollectionId == id);
        }
    }
}

src/CrowdSource.Web/Controllers/PresentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CrowdSource.Services;
using CrowdSource.Data;
using CrowdSource.Models.CoreModels;
using CrowdSource.Models.CoreViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace CrowdSource.Controllers
{
    public class PresentController : Controller
    {
        private readonly IDataLogic _logic;
        private readonly ApplicationDbContext _context;
        private readonly IDbConfig _config;

        public PresentController(ILoggerFactory loggerFactory, IDataLogic logic, ApplicationDbContext context, IDbConfig config)
        {
            _logic = logic;
            _context = context;
            _config = config;
        }


        [Route("Present/Collection/{id}")]
        public async Task<IActionResult> PresentGroupsInOneCollection([FromQuery]int? page,int id = 1)
        {

            ViewData["CollectionId"] = id;

            var types =  _logic.GetAllFieldTypes(id);

            var groups = new List<Group>();
            IQueryable<Group> @query;
            Pager @pager; 

            var minimumReview = _config.GetMinimumReview();

            @query = _context.Groups
                    .FromSql("SELECT * FROM \"Groups\" AS \"gg\"" +
                    "WHERE" +
                    "(SELECT COUNT(DISTINCT \"FieldTypes\".\"Name\") FROM" +
                    "  \"GVSuggestions\"" +
                    "   INNER JOIN \"GroupVersions\" ON \"GVSuggestions\".\"GroupVersionForeignKey\" = \"GroupVersions\".\"GroupVersionId\"" +
                    "   INNER JOIN \"FieldTypes\" ON \"GVSuggestions\".\"FieldTypeForeignKey\" = \"FieldTypes\".\"FieldTypeId\"" +
                    " WHERE \"GroupVersions\".\"GroupId\" = \"gg\".\"GroupId\"" +
                    " AND \"FieldTypes\".\"Name\" IN('TextBUC', 'TextEnglish', 'TextChinese')" +
                    " AND \"GroupVersions\".\"NextVersionGroupVersionId\" IS NULL" +
                    ") >= 3" + //罗 英 中 都有内容
                    "AND" +
                    "(" +
                    " SELECT COUNT(DISTINCT \"Reviews\".\"Id\") FROM \"Reviews\"" +
                    "   INNER JOIN \"GroupVersions\" ON \"Reviews\".\"GroupVersionId\" = \"GroupVersions\".\"GroupVersionId\"" +
                    "   WHERE \"GroupVersions\".\"GroupId\" = \"gg\".\"GroupId\"" +
                    "   AND \"GroupVersions\".\"NextVersionGroupVersionId\" IS NULL" +
                    ") >= {0}" +  // Review 不少于 minimumReview 次
                    " AND \"gg\".\"FlagType\" IS NULL",
                    minimumReview
                    )
                    .Where(g => g.Collection.CollectionId == id && g.FlagType == null);

            var count = await @query.CountAsync();
            @pager = new Pager(count, page ?? 1, 20);
            ViewData["pager"] = @pager;
            groups = await query.OrderBy(g => g.GroupId).Skip(@pager.PageSkip).Take(@pager.PageSize).ToListAsync();
            List<Dictionary<string,string>> groupsWithFields = new List<Dictionary<string,string>>(); 
            for (int i = 0; i< groups.Count; ++i) {
                var version = _logic.GetLastestVersion(groups[i].GroupId);
                var versionFields = _logic.GetVersionFields(version);
                var groupWithFields = new Dictionary<string,string> () {
                    {"TextBUC", versionFields[types.Single(t => t.Name == "TextBUC")]},
                    {"TextChinese", versionFields[types.Single(t => t.Name == "TextChinese")]},
                    {"TextEnglish", versionFields[types.Single(t => t.Name == "TextEnglish")]},
                };
                groupsWithFields.Add(groupWithFields);
            }
            ViewData["GroupsWithFields"] = groupsWithFields;
            return View("PresentGroup", groups);
        }

    }
}

src/CrowdSource.Web/Controllers/QueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using CrowdSource.Services;

namespace CrowdSource.Controllers
{
    [Authorize(Roles="Administrator")]
    public class QueueController : Controller
    {
        private ILogger<QueueController> _logger;
        private readonly ITaskDispatcher _taskDispatcher;

        public QueueController(ILoggerFactory loggerFactory, ITaskDispatcher taskDispatcher)
        {
            _logger = loggerFactory.CreateLogger<QueueController>();
            _taskDispatcher = taskDispatcher;
        }

        [Route("Admin/Queue/List")]
        public async Task<IActionResult> List([FromQuery]int? page)
        {
            Pager @pager;
            var todos = _taskDispatcher.ListToDo();
            @pager = new Pager(todos.Count(), page ?? 1, 20);
            ViewData["pager"] = @pager;
            var shownTodos = todos.Skip(@pager.PageSkip).Take(@pager.PageSize).ToList();
            ViewData["ToDo"] = shownTodos;
            ViewData["Doing"] = _taskDispatcher.ListDoing();
            return View("List");
        }


        [Route("Admin/Queue/ListReview")]
        public async Task<IActionResult> ListReview([FromQuery]int? page)
        {
            Pager @pager;
            var todos = _taskDispatcher.ListToReview();
            @pager = new Pager(todos.Count(), page ?? 1, 20);
            ViewData["pager"] = @pager;
            var shownTodos = todos.Skip(@pager.PageSkip).Take(@pager.PageSize).ToList();
            ViewData["ToReview"] = shownTodos;
            ViewData["Reviewing"] = _taskDispatcher.ListReviewing();
            return View("ListReview");
        }

        [Route("Admin/Queue/Reload")]
        public IActionResult Reload()
        {
            _taskDispatcher.Reload();
            return RedirectToAction("List");
        }

    }

}

src/CrowdSource.Web/Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using CrowdSource.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator"))
{
    <ul class="nav navbar-nav navbar-left">
        <li><a asp-area="" asp-controller="Collections" asp-action="Index">管理条目</a></li>
        <li><a asp-area="" asp-controller="Queue" asp-action="List">队列管理</a></li>
        <li><a asp-area="" asp-controller="Queue" asp-action="ListReview">队列管理(校对)</a></li>
        <li><a asp-area="" asp-controller="Admin" asp-action="Options">全局选项</a></li>
    </ul>
}

src/CrowdSource.Web/Views/Shared/_EditorLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 闽英众包</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/keyboard/dist/css/keyboard.min.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />
        <link rel="stylesheet" href="~/lib/uikit/css/uikit.min.css" />
        <link rel="stylesheet" href="~/lib/magnify/css/magnify.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tour/build/css/bootstrap-tour-standalone.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/previewer.css" />
        <link rel="stylesheet" href="~/css/editor.css" />   
        <link rel="stylesheet" href="~/css/keyboard-custom.css" /> 
    </environment>
    
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/keyboard/dist/css/keyboard.min.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" />
        <link rel="stylesheet" href="~/lib/uikit/css/uikit.min.css" />
        <link rel="stylesheet" href="~/lib/magnify/css/magnify.css">
        <link rel="stylesheet" href="~/lib/bootstrap-tour/build/css/bootstrap-tour-standalone.min.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="~/css/previewer.min.css" />
        <link rel="stylesheet" href="~/css/editor.min.css" />
        <link rel="stylesheet" href="~/css/keyboard-custom.css" asp-append-version="true"/>
    </environment>
</head>
<body>
@RenderBody()

@await Html.PartialAsync("_GoogleAnalyticsPartial")


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/magnify/js/jquery.magnify.js"></script>
        <script src="~/lib/keyboard/dist/js/jquery.keyboard.js"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js"></script>
        <script src="~/lib/bootstrap-tour/build/js/bootstrap-tour-standalone.js"></script>
        <script src="~/lib/uikit/js/uikit.min.js"></script>
        <script src="~/lib/mousetrap/mousetrap.min.js"></script>
        <script src="~/js/keyboard.layouts.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/editor.js" asp-append-version="true"></script>
        <script src="~/js/zoomer.js" asp-append-version="true"></script>
        <script src="~/js/attachKeyboards.js" asp-append-version="true"></script>
        <script src="~/js/previewer.js" asp-append-version="true"></script>
        <script src="~/js/editorModeSwitcher.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/lib/magnify/js/jquery.magnify.js"></script>
        <script src="~/lib/keyboard/dist/js/jquery.keyboard.min.js"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/jquery-ui.min.js"
                asp-fallback-src="~/lib/jquery-ui/jquery-ui.min.js"
                asp-fallback-test="window.jQuery.ui">
        </script>
        <script src="~/lib/bootstrap-tour/build/js/bootstrap-tour-standalone.min.js"></script>
        <script src="~/lib/uikit/js/uikit.min.js"></script>
        <script src="~/lib/mousetrap/mousetrap.min.js"></script>
        <script src="~/js/keyboard.layouts.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/CrowdSource.Web/Views/Shared/_EditorLoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using CrowdSource.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
        <ul class="uk-navbar-nav">
            <li>
                @{var HelloString = "已登录: "; }
                @HelloString@UserManager.GetUserName(User)!
            </li>
        </ul>
}
else
{
    <ul class="uk-navbar-nav">
        <li><a asp-area="" asp-controller="Account" asp-action="Login">匿名贡献中(登录可记录贡献)</a></li>
    </ul>
}

src/CrowdSource.Web/Views/Shared/_GoogleAnalyticsPartial.cshtml
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74530904-2', 'auto');
  ga('send', 'pageview');

</script>

src/CrowdSource.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 闽英众包</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/keyboard/dist/css/keyboard.min.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/previewer.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/keyboard-custom.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/keyboard/dist/css/keyboard.min.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" />
        <link rel="stylesheet" href="~/css/previewer.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/keyboard-custom.css" asp-append-version="true"/>
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CrowdSource</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">首页</a></li>
                    <li><a href="~/help/index.html" target="_blank">帮助</a></li>
                    <li><a asp-area="" asp-controller="Present" asp-route-id="1" asp-action="PresentGroupsInOneCollection">成果展示</a></li>
                    
                </ul>
                @await Html.PartialAsync("_AdminMenuPartial")
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - CrowdSource | Made with ♥ at <a href="http://lab.mindong.asia" target="_blank">MindongLab</a></p>
        </footer>
    </div>

@await Html.PartialAsync("_GoogleAnalyticsPartial")


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/keyboard/dist/js/jquery.keyboard.js"></script>
        <script src="~/lib/jquery-ui/jquery-ui.js"></script>
        <script src="~/lib/mousetrap/mousetrap.min.js"></script>
        <script src="~/js/keyboard.layouts.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/attachKeyboards.js" asp-append-version="true"></script>
        <script src="~/js/previewer.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/lib/keyboard/dist/js/jquery.keyboard.min.js"></script>
        <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
        <script src="~/lib/mousetrap/mousetrap.min.js"></script>
        <script src="~/js/keyboard.layouts.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/CrowdSource.Web/Views/Shared/_PreviewerPartial.cshtml
<table style="width: 100%;">
  <tbody>
    <tr style="vertical-align: top;">
        <td style="width: 13%;"></td>
        <td id="previewBUC">
        </td>
        <td style="width: 15%;">
            <span id="previewRadical"></span>
            <span id="previewChinese"></span>
            <span id="previewBoPoMoFo"></span>
            <span id="previewLabel"></span>
        </td>
        <td id="previewEnglish">
        </td>
        <td></td>
    </tr>
  </tbody>
</table>