src/CrowdSource.Web/Models/CoreViewModels/GroupDetailsViewModel.cs
using CrowdSource.Models.CoreModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrowdSource.Models.CoreViewModels
{
    public class GroupDetailsViewModel
    {
        public IEnumerable<Dictionary<FieldType, string>> Versions { get; set; }
        public List<GroupVersion> RawVersions { get; set; }
        public Group Group { get; set; }
        public IEnumerable<FieldType> FieldTypes { get; set; }
    }
}

src/CrowdSource.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CrowdSource.Services;
using CrowdSource.Data;
using CrowdSource.Models.CoreModels;
using CrowdSource.Models.CoreViewModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace CrowdSource.Controllers
{
    [Authorize(Roles="Administrator")]
    public class AdminController : Controller
    {
        private readonly IDataLogic _logic;
        private readonly ApplicationDbContext _context;
        private readonly IDbConfig _config;

        public AdminController(ILoggerFactory loggerFactory, IDataLogic logic, ApplicationDbContext context, IDbConfig config)
        {
            _logic = logic;
            _context = context;
            _config = config;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("Admin/Collection/{id}/Group")]
        public async Task<IActionResult> ListGroupsInOneCollection(int id, [FromQuery]string SearchFileName, [FromQuery]bool? ShowFlagged, [FromQuery]int? page)
        {

            ViewData["CollectionId"] = id;
            ViewData["SearchFileName"] = SearchFileName;
            ViewData["ShowFlagged"] = ShowFlagged ?? false;
            var groups = new List<Group>();
            IQueryable<Group> @query;
            Pager @pager; 
            if (ShowFlagged ?? false)
            {
                @query = _context.Groups.Where(g => g.Collection.CollectionId == id && g.FlagType != null);
            }
            else if (SearchFileName == null || SearchFileName == "")
            {
                @query = _context.Groups.Where(g => g.Collection.CollectionId == id);
            }
            else
            {
                @query = _context
                    .Groups
                    .FromSql("SELECT * FROM \"Groups\" WHERE \"GroupMetadata\"->>'ImgFileName' LIKE {0}", "%" + SearchFileName + "%")
                    .Where(g => g.Collection.CollectionId == id);       
            }
            var count = await @query.CountAsync();
            @pager = new Pager(count, page ?? 1, 20);
            ViewData["pager"] = @pager;
            groups = await query.OrderBy(g => g.GroupId).Skip(@pager.PageSkip).Take(@pager.PageSize).ToListAsync();
            return View("ListGroup", groups);
        }

        [Route("Admin/Group/{id}")]
        public IActionResult GroupDetails(int id)
        {
            //TODO: Authentication: Admin Only
            var versions = _logic.GetAllVersions(id);
            var versionsWithFields = new List<Dictionary<FieldType, string>>();
            foreach (var version in versions)
            {
                versionsWithFields.Add(_logic.GetVersionFields(version));
            }

            var vm = new GroupDetailsViewModel()
            {
                Group = _context.Groups.Single(g => g.GroupId == id),
                Versions = versionsWithFields,
                RawVersions = versions.ToList(),
                FieldTypes = _logic.GetAllFieldTypesByGroup(id)
            };

            return View("GroupDetails", vm);
        }

        [Route("Admin/Group/Delete/{id}")]
        public async Task<IActionResult> GroupDelete(int id)
        {
            var @group = await _context.Groups
                .Include(g=> g.Collection)
                .SingleOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View("GroupDeleteConfirm",@group);
        }

        [HttpPost]
        [Route("Admin/Group/Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GroupDeleteConfirmed(int id)
        {
            var @group = await _context.Groups
                .Include(g=>g.Collection)
                .SingleOrDefaultAsync(m => m.GroupId == id);
            var collectionId = @group.Collection.CollectionId;
            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();
            return RedirectToAction("ListGroupsInOneCollection",new { id = collectionId });
        }


        [Route("Admin/Group/UnsetError/{id}")]
        public async Task<IActionResult> UnsetGroupError(int id)
        {
            //TODO: auth admin
            var @group = await _context.Groups
                .SingleOrDefaultAsync(g => g.GroupId == id);
            @group.FlagType = null;
            await _context.SaveChangesAsync();
            return RedirectToAction("EditGroup", "CrowdSource", new { id = id });
        }


        [Route("Admin/Options")]
        public async Task<IActionResult> Options()
        {
            ViewData["ReviewEnabled"] = _config.Get("ReviewEnabled");
            ViewData["ReviewThreshold"] = _config.Get("ReviewThreshold");
            ViewData["Randomize"] = _config.Get("Randomize");
            return View();
        }

        [HttpPost]
        [Route("Admin/Options")]
        public async Task<IActionResult> OptionsSubmit([FromForm] string ReviewEnabled, [FromForm] string Randomize, [FromForm] int ReviewThreshold)
        {
            _config.Set("ReviewEnabled", ReviewEnabled);
            _config.Set("ReviewThreshold", ReviewThreshold.ToString());
            _config.Set("Randomize", Randomize);
            return RedirectToAction("Options");
        }

    }
}


public class Pager
{
    public int PageIndex { get; private set; }
    public int TotalPages { get; private set; }
    public int PageSize { get; private set; }

    public Pager(int count, int pageIndex, int pageSize)
    {
        PageIndex = pageIndex;
        TotalPages = (int)Math.Ceiling(count / (double)pageSize);
        PageSize = pageSize;
    }

    public bool HasPreviousPage
    {
        get
        {
            return (PageIndex > 1);
        }
    }

    public bool HasNextPage
    {
        get
        {
            return (PageIndex < TotalPages);
        }
    }
    public int PageSkip
    {
        get
        {
            return (PageIndex - 1) * PageSize;
        }
    }

}

src/CrowdSource.Web/ViewComponents/DisplayGroupViewComponent.cs
using CrowdSource.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrowdSource.ViewComponents
{
    public class DisplayGroupViewComponent : ViewComponent
    {
        private readonly IDataLogic _logic;

        public DisplayGroupViewComponent(IDataLogic logic)
        {
            _logic = logic;
        }

        public async Task<IViewComponentResult> InvokeAsync (int GroupId)
        {
            ViewData["FileName"] = GetGroupImgUrl(GroupId);
            return View("DisplayGroup","/segments/"+GetGroupImgUrl(GroupId));
        }

        private string GetGroupImgUrl(int GroupId)
        {
            Dictionary<string,string> meta = _logic.GetGroupMetadata(GroupId);
            return meta["ImgFileName"];

        }
    }
}

src/CrowdSource.Web/ViewComponents/GroupFileNameViewComponent.cs
using CrowdSource.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrowdSource.ViewComponents
{
    public class GroupFileNameViewComponent : ViewComponent
    {
        private readonly IDataLogic _logic;

        public GroupFileNameViewComponent(IDataLogic logic)
        {
            _logic = logic;
        }

        public async Task<IViewComponentResult> InvokeAsync (int GroupId)
        {
            return View("GroupFileName",GetGroupImgUrl(GroupId));
        }

        private string GetGroupImgUrl(int GroupId)
        {
            Dictionary<string,string> meta = _logic.GetGroupMetadata(GroupId);
            return meta["ImgFileName"];

        }
    }
}

src/CrowdSource.Web/Views/Admin/GroupDeleteConfirm.cshtml
@model CrowdSource.Models.CoreModels.Group

@{
    ViewData["Title"] = "确认删除？";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    @await Component.InvokeAsync("DisplayGroup", new { GroupId = Model.GroupId })
</div>
<div>
    <h4>Group @Model.GroupId</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
    
    <form asp-action="GroupDeleteConfirmed">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="ListGroupsInOneCollection" asp-route-id="@Model.Collection.CollectionId">Back to List</a>
        </div>
    </form>
</div>

src/CrowdSource.Web/Views/Admin/GroupDetails.cshtml
@model GroupDetailsViewModel
@{
    ViewData["Title"] = "条目历史";
}
<h1>View Group #@Model.Group.GroupId</h1>
@await Component.InvokeAsync("DisplayGroup", new { GroupId = Model.Group.GroupId })
<table class="table table-striped">
    <tr>
        <th>#</th>
        <th>Id</th>
        @foreach (var fieldType in Model.FieldTypes)
        {
            <th>
                @fieldType.Name (@fieldType.DataType)
            </th>
        }
        <th>创建时间</th>
        <th>Review Count</th>
    </tr>
    @{var i = 0; }
    @foreach (var version in Model.Versions)
    {
        <tr>
            <td>@(++i)</td>
            <td>@Model.RawVersions[i-1].GroupVersionId</td>
            @foreach (var fieldType in Model.FieldTypes)
            {
                <td>
                    @(version[fieldType] ?? "NULL")
                </td>
            }
            <td>@Model.RawVersions[i-1].Created</td>
            <td>@Model.RawVersions[i-1].UserReviews.Count</td>
            
        </tr>
    }
</table>

src/CrowdSource.Web/Views/Admin/ListGroup.cshtml
@model IEnumerable<Group>
@{
    ViewData["Title"] = "条目列表";
}

<form asp-controller="Admin"  asp-action="ListGroupsInOneCollection" method="get" role="form">
    SearchFileName:<input id="SearchFileName" name="SearchFileName" type="text" value="@ViewData["SearchFileName"]"/>
    Flagged: <input id="ShowFlagged" name="ShowFlagged" type="checkbox" value="true" checked="@((bool)ViewData["ShowFlagged"])" />
    <button type="submit" class="btn btn-primary">Filter</button>
</form>

<h1>Collection #@ViewData["CollectionId"] 中的全部条目</h1>

<table class="table table-bordered">
    <tr>
        <th>GroupId</th>
        <th>Image</th>
        <th>Actions</th>
        <th>Flags</th>
        
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.GroupId</td>
            <td>@await Component.InvokeAsync("DisplayGroup", new { GroupId = item.GroupId })
            @await Component.InvokeAsync("GroupFileName", new { GroupId = item.GroupId })</td>
            <td>
                <a>EditMetadata</a> |
                <a asp-controller="CrowdSource" asp-action="EditGroup" asp-route-id="@item.GroupId">编辑</a> | 
                <a asp-controller="Admin" asp-action="GroupDetails" asp-route-id="@item.GroupId">编辑历史</a> | 
                <a asp-controller="Admin" asp-action="GroupDelete" asp-route-id="@item.GroupId">Delete</a> 
            </td>
            <td>
                @item.FlagType?.ToString()
            </td>
        </tr>
    }
</table>

@{
    var pager = (Pager)ViewData["pager"];
    var prevDisabled = !pager.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !pager.HasNextPage ? "disabled" : "";
}

<a asp-action="ListGroupsInOneCollection"
   asp-route-ShowFlagged="@ViewData["ShowFlagged"]"
   asp-route-page="@(pager.PageIndex - 1)"
   asp-route-SearchFileName="@ViewData["SearchFileName"]"
   class="btn btn-default @prevDisabled btn">
    Previous
</a>
<a asp-action="ListGroupsInOneCollection"
   asp-route-ShowFlagged="@ViewData["ShowFlagged"]"
   asp-route-page="@(pager.PageIndex + 1)"
   asp-route-SearchFileName="@ViewData["SearchFileName"]"
   class="btn btn-default @nextDisabled btn">
    Next
</a>

Page @pager.PageIndex / @pager.TotalPages

src/CrowdSource.Web/Views/Admin/Options.cshtml
@{
    ViewData["Title"] = "全局选项";
}

<h1>全局选项</h1>

<form asp-controller="Admin" asp-action="OptionsSubmit" method="post" role="form">
  <div>
    开放“校对”: <input id="ReviewEnabled" name="ReviewEnabled" type="checkbox" value="true" checked="@((string)ViewData["ReviewEnabled"] == "true")" />
	</div>
   <div> 校对次数（每个词条版本被认为“已校对”所需的最少校对次数，默认2）<input id="ReviewThreshold" name="ReviewThreshold" type="number" value="@ViewData["ReviewThreshold"]" />
       <div>
           队列随机化: <input id="Randomize" name="Randomize" type="checkbox" value="true" checked="@((string)ViewData["Randomize"] == "true")" />
       </div>
	</div>
	    <button type="submit" class="btn btn-primary">保存</button>
</form>